// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Load .env.local first (takes precedence), then .env
import { config } from "dotenv";
import { resolve } from "path";

// Load .env.local first
config({ path: resolve(process.cwd(), ".env.local") });
// Then load .env (won't override .env.local values)
config({ path: resolve(process.cwd(), ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
